# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - :woman_technologist: ready for dev
  - :moneybag: bounty
  - :hand: bug
  - "🔐 security"
  - "👩‍💻 ready for dev"
  - "💰 bounty"
  - "✋ bug"

# Comment to post when removing the stale label.
unmarkComment: >
  Okay, it looks like this issue or feature request might still be important. We'll re-open
  it for now. Thank you for letting us know!
